import { formatCardPrompt, formatCardSummary, formatCardPromptAndHelpText, formatConfirmationDetails, MAX_CONFIRMATION_PROMPT_LENGTH, SafeCardPrompt, SafeCardSummary } from "./card-prompt.js";
import { createHash } from "node:crypto";
import { executePaperclipCommand, type PaperclipCommandResponse } from "@pilleo/paperclip-adapter-common";
import {
  extractJulesSessionId,
  extractJulesSessionIdFromComments,
  formatJulesSessionHandleBody,
  JULES_SESSION_DOCUMENT_KEY,
} from "./jules-session-handle.js";
const PAPERCLIP_API_URL_ENV = "PAPERCLIP_API_URL";

export class PaperclipClientError extends Error {
  constructor(public readonly status: number | null, message: string) {
    super(message);
    this.name = "PaperclipClientError";
  }
}

export interface PaperclipInteraction {
  id: string;
  status: string;
  kind?: string;
  result?: unknown;
  target?: unknown;
  idempotencyKey?: string;
}

export interface PlanRevision {
  documentId: string;
  revisionId: string;
  revisionNumber: number;
}

export interface PlanApprovalInteraction extends PaperclipInteraction {
  planRevision: PlanRevision;
}

export async function saveJulesPlanDocument(
  issueId: string, activityId: string, planMarkdown: string,
  authToken: string | undefined, runId?: string,
): Promise<PlanRevision> {
  let baseRevisionId: string | null = null;
  try {
    const headResponse = await paperclipRequest(`/api/issues/${encodeURIComponent(issueId)}/documents/plan`, authToken, { method: "GET" }, runId);
    const head = await headResponse.json() as Record<string, unknown>;
    baseRevisionId = typeof head["latestRevisionId"] === "string" ? head["latestRevisionId"] : null;
  } catch (error) {
    if (!(error instanceof PaperclipClientError) || error.status !== 404) throw error;
  }
  const response = await paperclipRequest(`/api/issues/${encodeURIComponent(issueId)}/documents/plan`, authToken, {
    method: "PUT",
    body: JSON.stringify({ title: "Jules plan", format: "markdown", body: planMarkdown, changeSummary: `Generated by Jules activity ${activityId}`, baseRevisionId }),
  }, runId);
  const document = await response.json() as Record<string, unknown>;
  if (typeof document["id"] !== "string" || typeof document["latestRevisionId"] !== "string" || typeof document["latestRevisionNumber"] !== "number") {
    throw new PaperclipClientError(response.status, "Paperclip returned an invalid plan document revision");
  }
  return { documentId: document["id"] as string, revisionId: document["latestRevisionId"] as string, revisionNumber: document["latestRevisionNumber"] as number };
}

function paperclipApiBaseUrl(): string {
  return (process.env[PAPERCLIP_API_URL_ENV] ?? "http://127.0.0.1:3100").replace(/\/+$/, "");
}

function isLocalTrustedPaperclip(): boolean {
  try {
    const host = new URL(paperclipApiBaseUrl()).hostname;
    return host === "127.0.0.1" || host === "localhost" || host === "::1";
  } catch {
    return false;
  }
}

function requireAuthToken(authToken: string | undefined): string | undefined {
  const token = (typeof authToken === "string" && authToken.trim().length > 0)
    ? authToken.trim()
    : process.env["PAPERCLIP_AGENT_TOKEN"] || process.env["PAPERCLIP_API_KEY"];
  if (token) return token;

  // Paperclip's `local_trusted` deployment is loopback-only and intentionally
  // has no agent/API key. Built-in adapters run inside that trusted process,
  // so requiring a credential here made every durable Jules write fail even
  // though the board itself correctly accepts unauthenticated local requests.
  // Keep the fallback limited to loopback; authenticated/remote deployments
  // still fail closed rather than silently sending bearer-less requests.
  const base = paperclipApiBaseUrl();
  if (/^https?:\/\/(127\.0\.0\.1|localhost)(:\d+)?$/i.test(base)) return undefined;
  throw new PaperclipClientError(null, "Paperclip local agent token is unavailable");
}

export async function getPaperclipJson<T>(
  path: string,
  authToken: string | undefined,
  runId?: string,
): Promise<T> {
  const response = await paperclipRequest(path, authToken, { method: "GET" }, runId);
  return (await response.json()) as T;
}

async function paperclipRequest(
  path: string,
  authToken: string | undefined,
  init: RequestInit,
  runId?: string,
): Promise<Response> {
  const token = requireAuthToken(authToken);
  const method = (init.method ?? "GET").toUpperCase();
  const isMutation = method !== "GET" && method !== "HEAD";
  const body = typeof init.body === "string" ? init.body : "";
  const bodyKey = body.match(/\"idempotencyKey\"\s*:\s*\"([^\"]+)\"/)?.[1];
  const idempotencyKey = bodyKey ?? (isMutation
    ? `jules:paperclip:${createHash("sha256").update(`${method}:${path}:${body}`).digest("hex")}`
    : undefined);
  let lastNetworkError: unknown;
  const command = {
    key: idempotencyKey ?? `jules:paperclip:read:${method}:${path}`,
    issueId: path.match(/\/api\/issues\/([^/]+)/)?.[1] ?? "unknown",
    action: isMutation ? "comment" as const : "status" as const,
    payload: { method, path },
  };
  const result = await executePaperclipCommand(command, async (): Promise<PaperclipCommandResponse> => {
    try {
      const response = await fetch(`${paperclipApiBaseUrl()}${path}`, {
        ...init,
        headers: {
          "Content-Type": "application/json",
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
          ...(effectiveRunId ? { "X-Paperclip-Run-Id": effectiveRunId } : {}),
          ...(idempotencyKey ? { "Idempotency-Key": idempotencyKey } : {}),
          ...init.headers,
        },
        signal: init.signal ?? AbortSignal.timeout(30_000),
      });
      return {
        ok: response.ok,
        status: response.status,
        data: response,
        ...(!response.ok && typeof response.text === "function"
          ? { text: await response.text().catch(() => "") }
          : {}),
      };
    } catch (error) {
      lastNetworkError = error;
      return { ok: false, status: 503, text: error instanceof Error ? error.message : String(error) };
    }
  });
  if (result.ok) return result.data as Response;
  if (lastNetworkError && result.status === 503) {
    throw new PaperclipClientError(null, `Paperclip API request failed: ${String(result.text ?? lastNetworkError)}`);
  }
  const suffix = result.text?.trim() ? ": " + result.text.trim().slice(0, 500) : "";
  throw new PaperclipClientError(result.status, "Paperclip API request failed (" + result.status + ")" + suffix);
}

// Used by durable ACP delegation helpers in this package. Keeping the request
// implementation here guarantees they use the same Paperclip auth and run attribution.
export const paperclipRequestForInternalUse = paperclipRequest;

async function moveIssue(
  issueId: string,
  status: "blocked" | "done" | "in_review" | "in_progress",
  authToken: string | undefined,
  comment?: string,
  runId?: string,
): Promise<void> {
  await paperclipRequest(`/api/issues/${encodeURIComponent(issueId)}`, authToken, {
    method: "PATCH",
    body: JSON.stringify({ status, ...(comment ? { comment } : {}) }),
  }, runId);
}

export async function listWorkProducts(
  issueId: string,
  authToken: string | undefined,
  runId?: string,
): Promise<Array<{ url?: string }>> {
  const response = await paperclipRequest(
    `/api/issues/${encodeURIComponent(issueId)}/work-products`,
    authToken,
    { method: "GET" },
    runId,
  );
  const raw: unknown = await response.json();
  return Array.isArray(raw)
    ? raw
        .filter(
            (w): w is Record<string, unknown> =>
                typeof w === "object" && w !== null && typeof (w as Record<string, unknown>)["url"] === "string",
        )
        .map((w) => ({ url: w["url"] as string }))
    : [];
}

/**
 * Idempotent by URL: a heartbeat retry after a timeout between the work-product
 * POST and the status PATCH would otherwise create duplicate primary PR cards.
 * (Issue #8)
 */
export async function upsertJulesSessionHandle(
  issueId: string,
  sessionId: string,
  sessionUrl: string | null | undefined,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  let baseRevisionId: string | null = null;
  try {
    const headResponse = await paperclipRequest(
      `/api/issues/${encodeURIComponent(issueId)}/documents/${JULES_SESSION_DOCUMENT_KEY}`,
      authToken,
      { method: "GET" },
      runId,
    );
    const head = await headResponse.json() as Record<string, unknown>;
    baseRevisionId = typeof head["latestRevisionId"] === "string" ? head["latestRevisionId"] : null;
  } catch (error) {
    if (!(error instanceof PaperclipClientError) || error.status !== 404) throw error;
  }

  await paperclipRequest(
    `/api/issues/${encodeURIComponent(issueId)}/documents/${JULES_SESSION_DOCUMENT_KEY}`,
    authToken,
    {
      method: "PUT",
      body: JSON.stringify({
        title: "Jules session",
        format: "markdown",
        body: formatJulesSessionHandleBody(sessionId, sessionUrl),
        changeSummary: `Jules session ${sessionId}`,
        baseRevisionId,
      }),
    },
    runId,
  );
}

export async function readJulesSessionHandle(
  issueId: string,
  authToken: string | undefined,
  runId?: string,
): Promise<string | null> {
  try {
    const response = await paperclipRequest(
      `/api/issues/${encodeURIComponent(issueId)}/documents/${JULES_SESSION_DOCUMENT_KEY}`,
      authToken,
      { method: "GET" },
      runId,
    );
    const document = await response.json() as Record<string, unknown>;
    const fromBody = extractJulesSessionId(typeof document["body"] === "string" ? document["body"] : null);
    if (fromBody) return fromBody;
  } catch (error) {
    if (!(error instanceof PaperclipClientError) || error.status !== 404) {
      /* fall through to comments */
    }
  }

  try {
    const comments = await listIssueComments(issueId, authToken, runId);
    return extractJulesSessionIdFromComments(comments);
  } catch {
    return null;
  }
}

/** Posts a standalone clickable Jules-session link as an issue comment. */
export async function postSessionLink(
  issueId: string,
  sessionUrl: string,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  await paperclipRequest(`/api/issues/${encodeURIComponent(issueId)}/comments`, authToken, {
    method: "POST",
    body: JSON.stringify({ body: `[Open Jules session](${sessionUrl})` }),
  }, runId);
}

export async function registerPullRequestWorkProduct(
  issueId: string,
  prUrl: string,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  const existing = await listWorkProducts(issueId, authToken, runId).catch(
    () => [] as Array<{ url?: string }>,
  );
  if (!existing.some((w) => w.url === prUrl)) {
    await paperclipRequest(`/api/issues/${encodeURIComponent(issueId)}/work-products`, authToken, {
      method: "POST",
      body: JSON.stringify({
        type: "pull_request",
        provider: "github",
        title: "Jules pull request",
        url: prUrl,
        externalId: prUrl,
        status: "ready_for_review",
        isPrimary: true,
        metadata: { source: "jules" },
      }),
    }, runId);
  }
}

export async function moveIssueToReview(
  issueId: string,
  prUrl: string,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  try {
    await registerPullRequestWorkProduct(issueId, prUrl, authToken, runId);
  } catch {
    // Work product registration is best-effort
  }

  // Note: We do not perform an unbacked status PATCH to in_review here to prevent
  // Paperclip server 422 invalid_issue_disposition errors on agent-authored transitions.
  // The Orchestrator automatically detects the registered PR and routes the task to in_review with a reviewer.
}

export async function moveIssueToInProgress(
  issueId: string,
  authToken: string | undefined,
  comment?: string,
  runId?: string,
): Promise<void> {
  await moveIssue(issueId, "in_progress", authToken, comment, runId);
}

export async function moveIssueToBlocked(
  issueId: string,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  await moveIssue(issueId, "blocked", authToken, undefined, runId);
}

export async function moveIssueToDone(
  issueId: string,
  sessionId: string,
  authToken: string | undefined,
  runId?: string,
  comment?: string,
): Promise<void> {
  await moveIssue(
    issueId,
    "done",
    authToken,
    comment ?? `Confirmed completion of Jules session ${sessionId}.`,
    runId,
  );
}

function interactionFromResponse(raw: unknown, status: number): PaperclipInteraction {
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    throw new PaperclipClientError(status, "Paperclip returned an invalid interaction response");
  }
  const record = raw as Record<string, unknown>;
  const id = record["id"];
  const interactionStatus = record["status"];
  if (typeof id !== "string" || id.length === 0 || typeof interactionStatus !== "string") {
    throw new PaperclipClientError(status, "Paperclip returned an invalid interaction response");
  }
  return {
    id,
    status: interactionStatus,
    result: record["result"],
    target: (record["payload"] as Record<string, unknown> | undefined)?.["target"] ?? record["target"],
    ...(typeof record["kind"] === "string" ? { kind: record["kind"] } : {}),
    ...(typeof record["idempotencyKey"] === "string" ? { idempotencyKey: record["idempotencyKey"] } : {}),
  };
}

export async function addJulesActivityComment(
  issueId: string,
  activityId: string,
  body: string,
  sessionUrl: string | undefined,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  await paperclipRequest(`/api/issues/${encodeURIComponent(issueId)}/comments`, authToken, {
    method: "POST",
    body: JSON.stringify({
      body,
      authorType: "agent",
    }),
  }, runId);
}

export async function createJulesFeedbackInteraction(
  issueId: string,
  sessionId: string,
  activityId: string,
  question: SafeCardPrompt | string,
  authToken: string | undefined,
  attempt = 1,
  runId?: string,
  summary?: SafeCardSummary | string,
): Promise<PaperclipInteraction> {
  const idempotencyKey = `jules:user-feedback:${issueId}:${sessionId}:${activityId}:${attempt}`;
  const { prompt: safePrompt, helpText: customHelpText } = formatCardPromptAndHelpText(typeof question === "string" ? question : String(question));
  const safeSummary = formatCardSummary(summary ?? question);
  try {
    const response = await paperclipRequest(
      `/api/issues/${encodeURIComponent(issueId)}/interactions`, authToken, {
        method: "POST",
        body: JSON.stringify({
          kind: "ask_user_questions",
          idempotencyKey,
          title: "Question from Jules",
          summary: safeSummary,
          continuationPolicy: "wake_assignee",
          payload: {
            version: 1,
            title: "Question from Jules",
            submitLabel: "Send to Jules",
            questions: [{
              id: "reply",
              prompt: safePrompt,
              helpText: customHelpText ? (customHelpText.slice(0, 930) + "\n\nType your answer or instructions for Jules below.") : "Type your answer or instructions for Jules below.",
              selectionMode: "single",
              required: true,
              options: [{ id: "response", label: "Write a response", freeText: true }],
            }],
          },
        }),
      },
      runId,
    );
    return interactionFromResponse(await response.json(), response.status);
  } catch (error) {
    if (error instanceof PaperclipClientError && (error.status === 409 || error.status === 422 || error.status === 400)) {
      const existing = await listPaperclipInteractions(issueId, authToken, runId).catch(() => []);
      const match = existing.find((i) => i.idempotencyKey === idempotencyKey) ||
        existing.find((i) => i.kind === "ask_user_questions");
      if (match) return match;
    }
    throw error;
  }
}

/**
 * Visible parent-thread record for a provider question handled by the strong
 * reviewer lane. It is intentionally not addressed to the reviewer: Jules
 * remains the parent assignee, while the executable reviewer form lives on a
 * Terra-owned child created by the adapters-only bridge.
 */
export async function createJulesAgentAdjudicationInteraction(
  issueId: string,
  sessionId: string,
  activityId: string,
  question: string,
  reviewerAgentId: string,
  authToken: string | undefined,
  runId?: string,
): Promise<PaperclipInteraction> {
  void reviewerAgentId;
  const idempotencyKey = `jules:agent-adjudication:${issueId}:${sessionId}:${activityId}`;
  const { prompt, helpText } = formatCardPromptAndHelpText(question);
  try {
    const response = await paperclipRequest(
      `/api/issues/${encodeURIComponent(issueId)}/interactions`, authToken, {
        method: "POST",
        body: JSON.stringify({
          kind: "ask_user_questions",
          idempotencyKey,
          title: "Jules question — strong review",
          summary: "A strong reviewer must choose an answer or escalation for Jules.",
          // The parent stays assigned to Jules. The reviewer wake target is
          // the Terra-owned child form created by the adapter below.
          continuationPolicy: "wake_assignee",
          resolverPolicy: "anyone",
          payload: {
            version: 1,
            title: "Jules question — strong review",
            submitLabel: "Submit reviewer decision",
            questions: [{
              id: "resolution",
              prompt: "Choose how to handle Jules' question.",
              helpText: "Answer only when the task context makes the response clear. Escalate concrete ambiguity to a human.",
              selectionMode: "single",
              required: true,
              options: [
                { id: "answer", label: "Answer Jules" },
                { id: "escalate", label: "Escalate to human" },
              ],
            }, {
              id: "response",
              prompt,
              helpText: helpText
                ? `${helpText.slice(0, 800)}\n\nProvide the exact answer for Jules, or the concrete ambiguity requiring human input. Submit this Paperclip form through its native respond endpoint using exactly: answers: [{ questionId: "resolution", optionIds: ["answer"] }, { questionId: "response", optionIds: ["response"], otherText: "..." }]. For escalation, use optionIds: ["escalate"] and put the concrete reason in otherText. Do not use selectedOptionIds, text, an object map, or an issue comment.`
                : "Provide the exact answer for Jules, or the concrete ambiguity requiring human input. Submit this Paperclip form through its native respond endpoint using exactly: answers: [{ questionId: \"resolution\", optionIds: [\"answer\"] }, { questionId: \"response\", optionIds: [\"response\"], otherText: \"...\" }]. For escalation, use optionIds: [\"escalate\"] and put the concrete reason in otherText. Do not use selectedOptionIds, text, an object map, or an issue comment.",
              selectionMode: "single",
              required: true,
              options: [{ id: "response", label: "Reviewer response", freeText: true }],
            }],
          },
        }),
      },
      runId,
    );
    return interactionFromResponse(await response.json(), response.status);
  } catch (error) {
    if (error instanceof PaperclipClientError && (error.status === 409 || error.status === 422 || error.status === 400)) {
      const existing = await listPaperclipInteractions(issueId, authToken, runId).catch(() => []);
      const match = existing.find((interaction) => interaction.idempotencyKey === idempotencyKey);
      if (match) return match;
    }
    throw error;
  }
}

/**
 * Creates the executable reviewer form on the reviewer-owned child issue.
 *
 * Paperclip wakes an addressed agent only when that agent owns the issue being
 * mutated.  The Jules issue must remain assigned to Jules, so its visible
 * audit card cannot also be the Terra wake target.  This child form is the
 * adapters-only compatibility bridge until Paperclip exposes a first-class
 * cross-assignee interaction target.
 */
export async function createJulesQuestionReviewInteraction(
  childIssueId: string,
  parentIssueId: string,
  sessionId: string,
  activityId: string,
  question: string,
  reviewerAgentId: string,
  authToken: string | undefined,
  runId?: string,
): Promise<PaperclipInteraction> {
  // Paperclip enforces interaction idempotency across more than one issue in
  // some deployments. Include the protocol child identity so a terminal
  // child from an earlier recovery generation cannot reject the new child's
  // otherwise-correct form with a cross-issue 409.
  const idempotencyKey = `jules:question-review:${childIssueId}:${parentIssueId}:${sessionId}:${activityId}`;
  const { prompt, helpText } = formatCardPromptAndHelpText(question);
  try {
    const response = await paperclipRequest(
      `/api/issues/${encodeURIComponent(childIssueId)}/interactions`, authToken, {
        method: "POST",
        body: JSON.stringify({
          kind: "ask_user_questions",
          idempotencyKey,
          title: "Adjudicate Jules question",
          summary: "A strong reviewer must choose an answer or escalation for Jules.",
          addresseeAgentId: reviewerAgentId,
          continuationPolicy: "wake_assignee",
          resolverPolicy: "anyone",
          payload: {
            version: 1,
            title: "Adjudicate Jules question",
            submitLabel: "Submit reviewer decision",
            questions: [{
              id: "resolution",
              prompt: "Choose how to handle Jules' question.",
              helpText: "Answer only when the task context makes the response clear. Escalate concrete ambiguity to a human.",
              selectionMode: "single",
              required: true,
              options: [
                { id: "answer", label: "Answer Jules" },
                { id: "escalate", label: "Escalate to human" },
              ],
            }, {
              id: "response",
              prompt,
              helpText: helpText
                ? `${helpText.slice(0, 800)}\n\nProvide the exact answer for Jules, or the concrete ambiguity requiring human input. Submit this Paperclip form through its native respond endpoint using exactly: answers: [{ questionId: "resolution", optionIds: ["answer"] }, { questionId: "response", optionIds: ["response"], otherText: "..." }]. For escalation, use optionIds: ["escalate"] and put the concrete reason in otherText. Do not use selectedOptionIds, text, an object map, or an issue comment.`
                : "Provide the exact answer for Jules, or the concrete ambiguity requiring human input. Submit this Paperclip form through its native respond endpoint using exactly: answers: [{ questionId: \"resolution\", optionIds: [\"answer\"] }, { questionId: \"response\", optionIds: [\"response\"], otherText: \"...\" }]. For escalation, use optionIds: [\"escalate\"] and put the concrete reason in otherText. Do not use selectedOptionIds, text, an object map, or an issue comment.",
              selectionMode: "single",
              required: true,
              options: [{ id: "response", label: "Reviewer response", freeText: true }],
            }],
          },
        }),
      },
      runId,
    );
    return interactionFromResponse(await response.json(), response.status);
  } catch (error) {
    if (error instanceof PaperclipClientError && (error.status === 409 || error.status === 422 || error.status === 400)) {
      const existing = await listPaperclipInteractions(childIssueId, authToken, runId).catch(() => []);
      const match = existing.find((interaction) => interaction.idempotencyKey === idempotencyKey);
      if (match) return match;
    }
    throw error;
  }
}

/** Record the strong reviewer's answer in the visible provider-question card. */
export async function answerJulesAgentAdjudicationInteraction(
  issueId: string,
  interactionId: string,
  answer: string,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  return resolveJulesAgentAdjudicationInteraction(issueId, interactionId, "answer", answer, authToken, runId);
}

/** Resolves the visible parent question card with the same typed decision used by the child form. */
export async function resolveJulesAgentAdjudicationInteraction(
  issueId: string,
  interactionId: string,
  resolution: "answer" | "escalate",
  responseText: string,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  try {
    await paperclipRequest(
      `/api/issues/${encodeURIComponent(issueId)}/interactions/${encodeURIComponent(interactionId)}/respond`,
      authToken,
      {
        method: "POST",
        body: JSON.stringify({
          answers: [
            { questionId: "resolution", optionIds: [resolution] },
            { questionId: "response", optionIds: ["response"], otherText: responseText },
          ],
          summaryMarkdown: resolution === "answer"
            ? "Resolved by the configured strong reviewer and relayed to Jules."
            : "Escalated by the configured strong reviewer for human clarification.",
        }),
      },
      runId,
    );
  } catch (error) {
    // Older parent cards were accidentally addressed to Terra. The child
    // form is the reviewer protocol, but Jules still has to close the parent
    // audit card after consuming Terra's answer. In local-trusted Paperclip,
    // retry once as the board actor; never discard a real adapter credential
    // or weaken authorization on authenticated deployments.
    if (error instanceof PaperclipClientError && error.status === 403 &&
        /interaction_addressee_mismatch/.test(error.message) && isLocalTrustedPaperclip()) {
      await paperclipRequest(
        `/api/issues/${encodeURIComponent(issueId)}/interactions/${encodeURIComponent(interactionId)}/respond`,
        undefined,
        {
          method: "POST",
          body: JSON.stringify({
            answers: [
              { questionId: "resolution", optionIds: [resolution] },
              { questionId: "response", optionIds: ["response"], otherText: responseText },
            ],
            summaryMarkdown: resolution === "answer"
              ? "Resolved by the configured strong reviewer and relayed to Jules."
              : "Escalated by the configured strong reviewer for human clarification.",
          }),
        },
      );
      return;
    }
    // Two Paperclip heartbeats may observe the same adjudication at once. If
    // the first one answered it, the second receives 409 rather than an
    // idempotent success. Re-fetch the authoritative interaction and treat an
    // already-answered card as success; every other 409 remains visible.
    if (error instanceof PaperclipClientError && error.status === 409) {
      const current = await getPaperclipInteraction(issueId, interactionId, authToken, runId).catch(() => null);
      if (current?.status === "answered") return;
    }
    throw error;
  }
}

export async function createJulesPlanApprovalInteraction(
  issueId: string,
  sessionId: string,
  activityId: string,
  planMarkdown: string,
  authToken: string | undefined,
  runId?: string,
): Promise<PlanApprovalInteraction> {
  const revision = await saveJulesPlanDocument(issueId, activityId, planMarkdown, authToken, runId);
  const { documentId, revisionId, revisionNumber } = revision;

  const response = await paperclipRequest(
    `/api/issues/${encodeURIComponent(issueId)}/interactions`, authToken, {
      method: "POST",
      body: JSON.stringify({
        kind: "request_confirmation",
        idempotencyKey: `confirmation:${issueId}:plan:${revisionId}`,
        title: "Approve Jules plan",
        summary: "Jules is waiting for plan approval.",
        continuationPolicy: "wake_assignee",
        payload: {
          version: 1,
          prompt: "Approve this Jules plan?",
          acceptLabel: "Approve plan",
          rejectLabel: "Request changes",
          rejectRequiresReason: true,
          rejectReasonLabel: "Requested changes",
          supersedeOnUserComment: true,
          target: {
            type: "issue_document",
            issueId,
            documentId,
            key: "plan",
            revisionId,
            revisionNumber,
            label: `Jules plan revision ${revisionNumber}`,
          },
        },
      }),
    },
    runId,
  );
  return {
    ...interactionFromResponse(await response.json(), response.status),
    planRevision: { documentId, revisionId, revisionNumber },
  };
}

export async function withdrawPaperclipInteraction(
  issueId: string,
  interactionId: string,
  reason: string,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  await paperclipRequest(
    `/api/issues/${encodeURIComponent(issueId)}/interactions/${encodeURIComponent(interactionId)}/withdraw`,
    authToken,
    {
      method: "POST",
      body: JSON.stringify({ reason }),
    },
    runId,
  );
}

export async function listPaperclipApprovals(
  companyId: string,
  authToken: string | undefined,
  runId?: string,
): Promise<Array<{ id: string; type: string; status: string; issueIds: string[]; payload?: Record<string, unknown> }>> {
  const raw = await getPaperclipJson<unknown>(
    `/api/companies/${encodeURIComponent(companyId)}/approvals`,
    authToken,
    runId,
  );
  const list = Array.isArray(raw)
    ? raw
    : raw && typeof raw === "object" && Array.isArray((raw as { approvals?: unknown }).approvals)
      ? (raw as { approvals: unknown[] }).approvals
      : [];
  return list
    .filter((item): item is Record<string, unknown> => Boolean(item) && typeof item === "object")
    .map((item) => ({
      id: String(item["id"] || ""),
      type: String(item["type"] || ""),
      status: String(item["status"] || ""),
      issueIds: Array.isArray(item["issueIds"]) ? item["issueIds"].map(String) : [],
      ...(item["payload"] && typeof item["payload"] === "object"
        ? { payload: item["payload"] as Record<string, unknown> }
        : {}),
    }));
}

export async function listPaperclipInteractions(
  issueId: string,
  authToken: string | undefined,
  runId?: string,
): Promise<PaperclipInteraction[]> {
  const response = await paperclipRequest(`/api/issues/${encodeURIComponent(issueId)}/interactions`, authToken, {
    method: "GET",
  }, runId);
  const raw: unknown = await response.json();
  if (!Array.isArray(raw)) return [];
  return raw.map((value) => interactionFromResponse(value, response.status));
}

export async function getPaperclipInteraction(
  issueId: string,
  interactionId: string,
  authToken: string | undefined,
  runId?: string,
): Promise<PaperclipInteraction | null> {
  const response = await paperclipRequest(`/api/issues/${encodeURIComponent(issueId)}/interactions`, authToken, {
    method: "GET",
  }, runId);
  const raw: unknown = await response.json();
  if (!Array.isArray(raw)) throw new PaperclipClientError(response.status, "Paperclip returned an invalid interactions response");
  const match = raw.find((value) => typeof value === "object" && value !== null && (value as Record<string, unknown>)["id"] === interactionId);
  return match ? interactionFromResponse(match, response.status) : null;
}

export async function createNoPrCompletionInteraction(
  issueId: string,
  sessionId: string,
  sessionUrl: string | undefined,
  authToken: string | undefined,
  runId?: string,
): Promise<PaperclipInteraction> {
  const details = [
    `Jules session: \`${sessionId}\``,
    sessionUrl ? `[Open the Jules session](${sessionUrl})` : null,
    "Accept to mark this task done. Reject to keep it blocked for manual follow-up.",
  ].filter((value): value is string => value !== null).join("\n\n");
  const response = await paperclipRequest(
    `/api/issues/${encodeURIComponent(issueId)}/interactions`,
    authToken,
    {
      method: "POST",
      body: JSON.stringify({
        kind: "request_confirmation",
        idempotencyKey: `jules:no-pr-completion:${issueId}:${sessionId}`,
        title: "Confirm Jules completion without a PR",
        summary: `Jules session ${sessionId} completed without creating a pull request.`,
        continuationPolicy: "wake_assignee",
        payload: {
          version: 1,
          prompt: "Jules completed without a PR. Is this task complete?",
          acceptLabel: "Mark done",
          rejectLabel: "Keep blocked",
          rejectRequiresReason: false,
          detailsMarkdown: details,
        },
      }),
    },
    runId,
  );
  return interactionFromResponse(await response.json(), response.status);
}

export async function createIssueComment(
  issueId: string,
  body: string,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  await paperclipRequest(
    `/api/issues/${encodeURIComponent(issueId)}/comments`,
    authToken,
    {
      method: "POST",
      body: JSON.stringify({ body }),
    },
    runId,
  );
}

export interface IssueComment {
  id: string;
  body: string;
  authorUserId?: string | null;
  authorAgentId?: string | null;
  createdAt: string;
}

export interface PaperclipIssue {
  id: string;
  identifier?: string | null;
  status: string;
  assigneeAgentId?: string | null;
  executionPolicy?: Record<string, unknown> | null;
  executionState?: Record<string, unknown> | null;
}

/**
 * Explicitly empty policy for adapter-owned reviewer children. `null` is not
 * equivalent here: Paperclip interprets null as permission to inherit/apply
 * the default review policy when the child is assigned.
 */
export const INTERNAL_REVIEW_EXECUTION_POLICY = {
  mode: "normal",
  stages: [],
  commentRequired: false,
} as const;

function executionPolicyWithJulesMonitor(
  executionPolicy: Record<string, unknown> | null | undefined,
  input: { sessionId: string; nextCheckAt: string; timeoutAt: string },
): Record<string, unknown> {
  // The Jules adapter owns provider continuation. Native Paperclip review
  // stages on the same issue can block a legitimate Jules poll or emit a
  // generic missing-disposition prompt, so retain only non-review metadata
  // while the remote session is active. The orchestrator owns final PR review.
  const { stages: _stages, commentRequired: _commentRequired, ...nonReviewPolicy } = executionPolicy ?? {};
  return {
    mode: nonReviewPolicy["mode"] ?? "normal",
    ...nonReviewPolicy,
    stages: [],
    commentRequired: false,
    monitor: {
      nextCheckAt: input.nextCheckAt,
      notes: "Jules cloud session is active; Paperclip will poll it when this monitor is due.",
      scheduledBy: "assignee",
      kind: "external_service",
      serviceName: "jules",
      externalRef: input.sessionId,
      timeoutAt: input.timeoutAt,
      recoveryPolicy: "wake_owner",
    },
  };
}

/**
 * Persists Paperclip's native durable continuation for a live Jules session.
 * The monitor scheduler atomically claims the due check and wakes this issue's
 * assignee, so no adapter-private timer or orchestrator poll is required.
 */
export async function scheduleJulesSessionMonitor(
  issueId: string,
  sessionId: string,
  nextCheckAt: string,
  timeoutAt: string,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  const issue = await getPaperclipIssue(issueId, authToken, runId);
  await paperclipRequest(`/api/issues/${encodeURIComponent(issueId)}`, authToken, {
    method: "PATCH",
    body: JSON.stringify({
      executionPolicy: executionPolicyWithJulesMonitor(issue.executionPolicy, {
        sessionId,
        nextCheckAt,
        timeoutAt,
      }),
    }),
  }, runId);
}

/** Remove only the Jules continuation marker and retain any review workflow. */
export async function clearJulesSessionMonitor(
  issueId: string,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  const issue = await getPaperclipIssue(issueId, authToken, runId);
  const policyMonitor = issue.executionPolicy?.["monitor"];
  const stateMonitor = issue.executionState?.["monitor"];
  const strandedJulesMonitor = !policyMonitor && stateMonitor &&
    typeof stateMonitor === "object" && !Array.isArray(stateMonitor) &&
    (stateMonitor as Record<string, unknown>)["serviceName"] === "jules" &&
    typeof (stateMonitor as Record<string, unknown>)["externalRef"] === "string";
  if (!policyMonitor && !strandedJulesMonitor) return;

  let policy: Record<string, unknown> = issue.executionPolicy ?? { ...INTERNAL_REVIEW_EXECUTION_POLICY };
  if (strandedJulesMonitor) {
    // Compatibility bridge for Paperclip versions that strip executionPolicy
    // when a monitor is triggered but leave executionState.monitor behind.
    // Reintroduce the same Jules monitor, then remove it through the normal
    // policy transition so Paperclip clears both projections. This is safe to
    // repeat and must be removed once Paperclip exposes a direct clear API.
    const monitor = stateMonitor as Record<string, unknown>;
    policy = executionPolicyWithJulesMonitor(policy, {
      sessionId: String(monitor["externalRef"]),
      nextCheckAt: new Date(Date.now() + 5 * 60 * 1000).toISOString(),
      timeoutAt: typeof monitor["timeoutAt"] === "string"
        ? monitor["timeoutAt"]
        : new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    });
    await paperclipRequest(`/api/issues/${encodeURIComponent(issueId)}`, authToken, {
      method: "PATCH",
      body: JSON.stringify({ executionPolicy: policy }),
    }, runId);
  }

  const { monitor: _monitor, ...executionPolicy } = policy;
  await paperclipRequest(`/api/issues/${encodeURIComponent(issueId)}`, authToken, {
    method: "PATCH",
    body: JSON.stringify({
      executionPolicy: Object.keys(executionPolicy).length > 0 ? executionPolicy : null,
    }),
  }, runId);

  if (strandedJulesMonitor) {
    const verified = await getPaperclipIssue(issueId, authToken, runId);
    const remaining = verified.executionState?.["monitor"];
    if (remaining && typeof remaining === "object" && !Array.isArray(remaining) &&
        (remaining as Record<string, unknown>)["serviceName"] === "jules") {
      throw new PaperclipClientError(null, "Paperclip retained a stranded Jules monitor after compatibility cleanup");
    }
  }
}

export async function createJulesQuestionAdjudication(
  parentIssueId: string,
  reviewerAgentId: string,
  question: string,
  authToken: string | undefined,
  runId?: string,
  companyId?: string,
  activityId?: string,
  sessionId?: string,
  generation = 0,
  deferExecution = false,
): Promise<PaperclipIssue> {
  const fingerprint = createHash("sha256").update(question).digest("hex").slice(0, 24);
  const correlation = companyId && activityId
    ? buildQuestionCorrelation({
      parentIssueId,
      companyId,
      sessionId: sessionId ?? "unknown-session",
      activityId,
      reviewerAgentId,
      question,
      generation,
    })
    : null;
  const marker = correlation
    ? questionCorrelationMarker(correlation)
    : `<!-- jules-question-adjudication:${fingerprint} -->`;
  const lockKey = `${parentIssueId}:${activityId ?? fingerprint}:${generation}`;
  const description = `
${marker}
You are the strong adjudicator for a Jules provider question. Answer only the quoted operational question. Do not inspect or review the checkout, diff, tests, branches, pull requests, GitHub, or repository files; they may be stale and are not part of this decision. Do not propose code changes or implementation feedback. Use only the parent task's explicit instructions and the quoted provider question. For generic continue/commit/submit questions, return the direct workflow instruction already declared by the parent task. Escalate only when the question requires a concrete product or authorization decision that the parent task does not specify.

Provider question:
${question}

The Paperclip interaction attached to this issue is the only decision protocol. Submit
that typed form with either an answer for Jules or an escalation for a human, then
mark this adjudication task done. Do not post a JSON object, review findings, or
implementation advice as an issue comment.`;
  const previous = questionAdjudicationLocks.get(lockKey) ?? Promise.resolve();
  const operation = previous.then(async () => {
    if (companyId) {
      const issues = await getPaperclipJson<Array<Record<string, unknown>> | { issues?: Array<Record<string, unknown>> }>(
        `/api/companies/${encodeURIComponent(companyId)}/issues?limit=1000`, authToken, runId,
      ).catch(() => [] as Array<Record<string, unknown>>);
      const list = Array.isArray(issues) ? issues : (issues.issues ?? []);
      const existing = list.find((issue) =>
        issue["parentId"] === parentIssueId &&
        (deferExecution || issue["assigneeAgentId"] === reviewerAgentId) &&
        typeof issue["description"] === "string" &&
        (issue["description"] as string).includes(marker) &&
        issue["status"] !== "cancelled" && issue["status"] !== "done",
      );
      if (existing && typeof existing["id"] === "string") return existing as unknown as PaperclipIssue;
    }
    let created: PaperclipIssue;
    try {
      const response = await paperclipRequest(
        `/api/issues/${encodeURIComponent(parentIssueId)}/children`, authToken, {
        method: "POST",
        body: JSON.stringify({
          title: "Adjudicate Jules provider question",
          description,
          // Paperclip treats `blocked` as closed for interaction creation.
          // Backlog accepts interactions but is not eligible for an agent
          // heartbeat. Keep Terra assigned so Paperclip can surface the
          // pending form when activation changes the status to todo.
          status: deferExecution ? "backlog" : "todo",
          priority: "high",
          assigneeAgentId: reviewerAgentId,
          // Jules owns the provider-question gate. A native Paperclip dependency
          // would block the parent before the adapter can consume the reviewer's
          // structured answer and would invite generic native recovery prompts.
          blockParentUntilDone: false,
          executionPolicy: INTERNAL_REVIEW_EXECUTION_POLICY,
        }),
        }, runId,
      );
      created = (await response.json()) as PaperclipIssue;
    } catch (error) {
      if (!isPaperclipChildLimitError(error) || !companyId) throw error;
      // Paperclip intentionally caps helper children per parent. Use a fresh
      // company-level protocol issue when that cap is hit. Reopening a
      // terminal child would retain its old reviewer comments and could make
      // a stale answer look like the answer to this new provider question.
      const raw = await getPaperclipJson<unknown>(
        `/api/companies/${encodeURIComponent(companyId)}/issues?limit=1000`, authToken, runId,
      );
      const allIssues = Array.isArray(raw) ? raw : ((raw as { issues?: unknown[] })?.issues ?? []);
      const alreadyCreated = allIssues.find((value) => {
        const issue = value as Record<string, unknown>;
        return issue["status"] !== "cancelled" && issue["status"] !== "done" &&
          typeof issue["description"] === "string" &&
          (issue["description"] as string).includes(marker) &&
          typeof issue["id"] === "string";
      });
      if (alreadyCreated && typeof (alreadyCreated as Record<string, unknown>)["id"] === "string") {
        created = alreadyCreated as PaperclipIssue;
      } else {
        const response = await paperclipRequest(
          `/api/companies/${encodeURIComponent(companyId)}/issues`, authToken, {
          method: "POST",
          body: JSON.stringify({
            companyId,
            title: "Adjudicate Jules provider question",
            description: `${description}\n\nParent issue: ${parentIssueId}`,
            status: deferExecution ? "backlog" : "todo",
            priority: "high",
            assigneeAgentId: reviewerAgentId,
            blockParentUntilDone: false,
            executionPolicy: INTERNAL_REVIEW_EXECUTION_POLICY,
          }),
          }, runId,
        );
        created = (await response.json()) as PaperclipIssue;
      }
      /*
       * The fallback intentionally has no parentId: it is still linked by its
       * marker and session state, while avoiding Paperclip's per-parent cap.
       */
      if (!created.id) throw error;
      await paperclipRequest(`/api/issues/${encodeURIComponent(created.id)}`, authToken, {
        method: "PATCH",
        body: JSON.stringify({
          assigneeAgentId: reviewerAgentId,
          blockParentUntilDone: false,
          executionPolicy: INTERNAL_REVIEW_EXECUTION_POLICY,
        }),
      }, runId);
    }
    // Paperclip versions that inherit the parent's policy on child creation
    // must be explicitly neutralized. This child is an ACP protocol endpoint,
    // not a native execution-review task.
    if (created.id) {
      await paperclipRequest(`/api/issues/${encodeURIComponent(created.id)}`, authToken, {
        method: "PATCH",
        body: JSON.stringify({ blockParentUntilDone: false, executionPolicy: INTERNAL_REVIEW_EXECUTION_POLICY }),
      }, runId).catch(() => undefined);
    }
    return created;
  });
  const lock = operation.then(() => undefined, () => undefined);
  questionAdjudicationLocks.set(lockKey, lock);
  try { return await operation; } finally {
    if (questionAdjudicationLocks.get(lockKey) === lock) questionAdjudicationLocks.delete(lockKey);
  }
}

const questionAdjudicationLocks = new Map<string, Promise<void>>();

export async function getPaperclipIssue(
  issueId: string,
  authToken: string | undefined,
  runId?: string,
): Promise<PaperclipIssue> {
  return getPaperclipJson<PaperclipIssue>(`/api/issues/${encodeURIComponent(issueId)}`, authToken, runId);
}

/**
 * Internal Jules reviewer children are protocol endpoints, not Paperclip review
 * tasks. Paperclip can attach the parent's execution policy when assigning a
 * child, so repair that policy immediately before consuming the child result.
 * This is intentionally idempotent and keeps provider-question adjudication
 * out of native review/approval loops.
 */
export async function normalizeInternalReviewIssue(
  issue: PaperclipIssue,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  if (issue.executionPolicy &&
      Array.isArray(issue.executionPolicy["stages"]) &&
      issue.executionPolicy["stages"].length === 0 &&
      issue.executionPolicy["commentRequired"] === false) return;
  await paperclipRequest(`/api/issues/${encodeURIComponent(issue.id)}`, authToken, {
    method: "PATCH",
    body: JSON.stringify({ blockParentUntilDone: false, executionPolicy: INTERNAL_REVIEW_EXECUTION_POLICY }),
  }, runId);
}

/** Completes an internal reviewer child after its structured protocol result is consumed. */
export async function completeInternalReviewIssue(
  issueId: string,
  authToken: string | undefined,
  runId?: string,
): Promise<void> {
  await paperclipRequest(`/api/issues/${encodeURIComponent(issueId)}`, authToken, {
    method: "PATCH",
    body: JSON.stringify({ status: "done", blockParentUntilDone: false, executionPolicy: INTERNAL_REVIEW_EXECUTION_POLICY }),
  }, runId);
}

export async function listIssueComments(
  issueId: string,
  authToken: string | undefined,
  runId?: string,
): Promise<IssueComment[]> {
  const response = await paperclipRequest(
    `/api/issues/${encodeURIComponent(issueId)}/comments`,
    authToken,
    { method: "GET" },
    runId,
  );
  const raw = (await response.json()) as unknown;
  return Array.isArray(raw) ? (raw as IssueComment[]) : [];
}
