import { z } from "zod";
import type {
  ServerAdapterModule,
  AdapterEnvironmentTestContext,
  AdapterEnvironmentTestResult,
  AdapterConfigSchema,
  AdapterExecutionContext,
  AdapterExecutionResult,
} from "@paperclipai/adapter-utils";
import { PaperclipTelegramPlugin } from "../plugin.js";

export const TelegramConfigSchema = z.object({
  botToken: z.string().min(1, "Telegram Bot Token is required"),
  allowedUserIds: z.array(z.number().int()).min(1, "At least one allowed user ID is required"),
  defaultChatId: z.union([z.string(), z.number()]).optional(),
  paperclipApiUrl: z.string().url().default("http://127.0.0.1:3100"),
  paperclipApiKey: z.string().optional(),
  paperclipCompanyId: z.string().optional(),
  pollIntervalMs: z.number().int().min(1000).default(3000),
  notifications: z
    .object({
      approvals: z.boolean().default(true),
      clarifications: z.boolean().default(true),
      ciFailures: z.boolean().default(true),
      dailyDigest: z.boolean().default(true),
    })
    .default({
      approvals: true,
      clarifications: true,
      ciFailures: true,
      dailyDigest: true,
    }),
});

export type TelegramConfig = z.infer<typeof TelegramConfigSchema>;

export const telegramAdapterConfigSchema: AdapterConfigSchema = {
  fields: [
    {
      key: "botToken",
      label: "Telegram Bot Token",
      type: "text",
      required: true,
      hint: "HTTP API Bot Token generated by @BotFather on Telegram",
    },
    {
      key: "allowedUserIds",
      label: "Allowed Operator User IDs",
      type: "text",
      required: true,
      hint: "Comma-separated list of Telegram user IDs authorized to approve tasks (e.g. 123456789)",
    },
    {
      key: "defaultChatId",
      label: "Default Notification Chat / Channel ID",
      type: "text",
      required: false,
      hint: "Telegram Chat ID where approval cards and status updates will be posted",
    },
    {
      key: "pollIntervalMs",
      label: "Polling Interval (ms)",
      type: "number",
      required: false,
      default: 3000,
      hint: "Interval to check Paperclip for pending approvals (default: 3000ms)",
    },
  ],
};

export const telegramAgentConfigurationDoc = `# Telegram Operator Companion Plugin

Enables real-time remote approvals, threaded Q&A clarifications, and telemetry monitoring directly from Telegram.

---

## 🚀 Capabilities
- **One-Tap Approvals:** Receive PR approval cards on Green CI with \`[ ✅ Approve & Merge ]\` / \`[ ❌ Request Changes ]\` inline buttons.
- **Threaded Clarification Answers:** Reply directly to agent questions in chat to feed instructions back into Paperclip issue comments.
- **Fleet Telemetry:** Query \`/status\` and \`/queue\` for live worker counts and rolling cloud spend.
- **Security Whitelist:** Enforces strict operator user ID filtering to prevent unauthorized callbacks.
`;

export async function testEnvironment(
  ctx: AdapterEnvironmentTestContext,
): Promise<AdapterEnvironmentTestResult> {
  const config = (ctx as any).config || (ctx as any).adapterConfig || {};
  const token = typeof config["botToken"] === "string" ? config["botToken"].trim() : process.env["TELEGRAM_BOT_TOKEN"];

  if (!token) {
    return {
      adapterType: "telegram",
      status: "fail",
      testedAt: new Date().toISOString(),
      checks: [
        {
          code: "telegram_token_missing",
          level: "error",
          message: "Telegram Bot Token is not configured",
          detail: "Set botToken in plugin settings or TELEGRAM_BOT_TOKEN in environment",
          hint: "Create a bot with @BotFather on Telegram and copy the API token",
        },
      ],
    };
  }

  try {
    const res = await fetch(`https://api.telegram.org/bot${token}/getMe`);
    if (!res.ok) {
      return {
        adapterType: "telegram",
        status: "fail",
        testedAt: new Date().toISOString(),
        checks: [
          {
            code: "telegram_auth_failed",
            level: "error",
            message: `Telegram API returned status ${res.status}`,
            detail: await res.text(),
            hint: "Check that your Telegram Bot Token is valid and active",
          },
        ],
      };
    }

    const data = (await res.json()) as { ok: boolean; result?: { username?: string; first_name?: string } };
    const botName = data.result?.username ? `@${data.result.username}` : "Telegram Bot";

    return {
      adapterType: "telegram",
      status: "pass",
      testedAt: new Date().toISOString(),
      checks: [
        {
          code: "telegram_bot_connected",
          level: "info",
          message: `Connected successfully to Telegram Bot: ${botName}`,
          detail: null,
          hint: null,
        },
      ],
    };
  } catch (err: any) {
    return {
      adapterType: "telegram",
      status: "fail",
      testedAt: new Date().toISOString(),
      checks: [
        {
          code: "telegram_network_error",
          level: "error",
          message: `Failed to reach Telegram Bot API: ${err.message}`,
          detail: null,
          hint: "Check network connectivity to https://api.telegram.org",
        },
      ],
    };
  }
}

export function createServerAdapter(): ServerAdapterModule {
  return {
    type: "telegram",
    execute: async (_ctx: AdapterExecutionContext): Promise<AdapterExecutionResult> => {
      const plugin = new PaperclipTelegramPlugin();
      await plugin.register();
      return {
        exitCode: 0,
        signal: null,
        timedOut: false,
        summary: "Telegram companion active",
      };
    },
    testEnvironment,
    supportsLocalAgentJwt: true,
    supportsInstructionsBundle: false,
    models: [],
    modelProfiles: [],
    listModels: async () => [],
    listModelProfiles: async () => [],
    agentConfigurationDoc: telegramAgentConfigurationDoc,
    getConfigSchema: () => telegramAdapterConfigSchema,
  };
}

export default createServerAdapter;
