export const manifest = {
  id: "telegram",
  apiVersion: 1 as const,
  version: "0.1.0",
  displayName: "Telegram Operator Companion",
  description: "Real-time Telegram notifications, interactive PR approval cards, and agent clarifications.",
  author: "Pilleo",
  categories: ["connector" as const, "automation" as const],
  capabilities: [
    "companies.read" as const,
    "issues.read" as const,
    "issue.comments.read" as const,
    "issue.comments.create" as const,
    "issue.comments.create_human_attributed" as const,
    "approvals.read" as const,
    "approvals.respond" as const,
    "events.subscribe" as const,
    "http.outbound" as const,
  ],
  entrypoints: {
    worker: "./dist/worker.js",
  },
  instanceConfigSchema: {
    type: "object",
    properties: {
      botToken: {
        type: "string",
        title: "Telegram Bot Token",
        description: "Bot token generated by @BotFather on Telegram",
      },
      allowedUserIds: {
        type: "string",
        title: "Allowed Operator User IDs",
        description: "Comma-separated list of authorized Telegram user IDs",
      },
      defaultChatId: {
        type: "string",
        title: "Default Chat / Channel ID",
        description: "Telegram chat or channel ID for notifications",
      },
      pollIntervalMs: {
        type: "number",
        title: "Polling Interval (ms)",
        description: "Interval to check Paperclip for pending approvals (default: 3000ms)",
        default: 3000,
      },
    },
    required: ["botToken", "allowedUserIds"],
  },
};

export default manifest;
